version: "3.7"

services:
  web:
    image: webdevops/php-apache:alpine-php7
    container_name: apache-matheus
    ports:
      - "4500:80"
    volumes:
      - /home/matheus/BootcampTQI-DIO/Docker/php:/app

    networks:
      - minha-rede

  db:
    image: mysql:5.7
    container_name: mysql-matheus
    environment:
      MYSQL_ROOT_PASSWORD: "Senha123"
      MYSQL_DATABASE: "testedb"
    ports:
      - "3306:3306"
    volumes:
      - /home/matheus/BootcampTQI-DIO/Docker/mysql-C:/var/lib/mysql

    networks:
      - minha-rede

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-matheus
    environment:
      MYSQL_ROOT_PASSWORD: "Senha123"
    ports:
      - "8080:8080"
    volumes:
      - /home/matheus/BootcampTQI-DIO/Docker/php/admin/uploads.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini

    networks:
      - minha-rede

networks:
   minha-rede:
     driver: bridge
