version: "3.7"

services:
  html:
    image: httpd:latest
    container_name: matheus-html
    restart: always
    ports:
    - '8080:80'
    volumes:
    - /home/matheus/BootcampTQI-DIO/Docker/desafio-docker/Site:/usr/local/apache2/htdocs/

    networks:
      - minha-rede
        
  DataB:
    image: mysql:5.7
    container_name: matheus-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "senha"
      MYSQL_DATABASE: "admin"
    ports:
      - "3306:3306"
    volumes:
      - /home/matheus/BootcampTQI-DIO/Docker/desafio-docker/BancoSQL:/var/lib/mysql

    networks:
      - minha-rede

  adminer:
    image: adminer
    container_name: matheus-adminer
    restart: always
    ports:
      - 80:8080

    networks:
      - minha-rede

networks: 
  minha-rede:
    driver: bridge

